ruvents_admin:
    menu:
        -
            title: На сайт
            url: /
            attributes: { target: _blank, icon: fa-home }
        -
            title: Пользователи
            attributes: { icon: fa-users }
            active: "entity === 'user'"
            children:
                - { title: Список, entity: 'user:list' }
                - { title: Создать, entity: 'user:create' }
        -
            title: Группы
            attributes: { icon: fa-bars }
            active: "entity === 'group'"
            children:
                - { title: Список, entity: 'group:list' }
                - { title: Создать, entity: 'group:create' }
    entities:
        user:
            class: App\Entity\User
            list:
                title: Список пользователей
                per_page: 2
                fields:
                    - '@id'
                    - '@title'
                    - text
                    - simpleArray
                    - date
                    - group
                    - groups
                    - '@actions'
            create:
                title: Создание пользователя
                fields:
                    - text
            edit:
                title: Редактирование пользователя
                fields:
                    - text@markdown
                    - simpleArray[0]
                    - '@group{Title}'
                    - group
                    - groups
        group:
            class: App\Entity\Group
