ruvents_admin:
    menu:
        -
            title: На сайт
            url: /
            attributes: { target: _blank, icon: ion-home }
        -
            title: Пользователи
            attributes: { icon: ion-person-stalker }
            active: "entity === 'user'"
            children:
                - { title: Список, entity: 'user:list', active: "entity === 'user' and route === 'ruvents_admin_edit'" }
                - { title: Создать, entity: 'user:create' }
    entities:
        user:
            class: App\Entity\User
            list:
                fields:
                    - text@raw{Текст}
            create:
                title: Редактирование пользователя
                fields:
                    - text
            edit:
                title: Редактирование пользователя
                fields:
                    - text
