framework:
    secret: '%env(APP_SECRET)%'
    default_locale: ru
    csrf_protection: ~
    session:
        handler_id: ~
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    ide: phpstorm
