services:
  ruwork_admin.form.extension.form:
    class: AppBundle\Form\Extension\FormTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  ruwork_admin.form.extension.button:
    class: AppBundle\Form\Extension\ButtonTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

  ruwork_admin.twig.extension.form:
    class: Ruwork\AdminBundle\Twig\Extension\FormExtension
    public: false
    tags:
      - { name: twig.extension }
